version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      # Restore cache from last test run
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: yarn

      # Save cache for a future test run
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run tests"
          command: yarn test-ci
